export const Types = {
	FETCH_ALL_POKEMONS: 'FETCH_POKEMONS',

	FETCH_POKEMONS_LIST_START: 'FETCH_POKEMONS_LIST_START',
	FETCH_POKEMONS_LIST_SUCCESS: 'FETCH_POKEMONS_LIST_SUCCESS',
	FETCH_POKEMONS_LIST_FAILURE: 'FETCH_POKEMONS_LIST_FAILURE',

	POKEMON_DETAILS: 'POKEMON_DETAILS',
	FETCH_POKEMON_DETAILS_SUCCESS: 'FETCH_POKEMON_DETAILS_SUCCESS',
	FETCH_POKEMON_DETAILS_START: 'FETCH_POKEMON_DETAILS_START',
	FETCH_POKEMON_DETAILS_FAILURE: 'FETCH_POKEMON_DETAILS_FAILURE',

	FETCH_POKEMON_TYPES_SUCCESS: 'FETCH_POKEMON_TYPES_SUCCESS',
	FETCH_POKEMON_TYPES_ERROR: 'FETCH_POKEMON_TYPES_ERROR',
}
